comptevoyageur_index:
    path:     /
    defaults: { _controller: "GestionBundle:CompteVoyageur:index" }
    methods:  GET

comptevoyageur_show:
    path:     /{id}/show
    defaults: { _controller: "GestionBundle:CompteVoyageur:show" }
    methods:  GET

comptevoyageur_new:
    path:     /new
    defaults: { _controller: "GestionBundle:CompteVoyageur:new" }
    methods:  [GET, POST]

comptevoyageur_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionBundle:CompteVoyageur:edit" }
    methods:  [GET, POST]

comptevoyageur_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionBundle:CompteVoyageur:delete" }
    methods:  DELETE
