gare_index:
    path:     /
    defaults: { _controller: "GestionBundle:Gare:index" }
    methods:  GET

gare_show:
    path:     /{id}/show
    defaults: { _controller: "GestionBundle:Gare:show" }
    methods:  GET

gare_new:
    path:     /new
    defaults: { _controller: "GestionBundle:Gare:new" }
    methods:  [GET, POST]

gare_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionBundle:Gare:edit" }
    methods:  [GET, POST]

gare_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionBundle:Gare:delete" }
    methods:  DELETE
