ville_index:
    path:     /
    defaults: { _controller: "GestionBundle:Ville:index" }
    methods:  GET

ville_show:
    path:     /{id}/show
    defaults: { _controller: "GestionBundle:Ville:show" }
    methods:  GET

ville_new:
    path:     /new
    defaults: { _controller: "GestionBundle:Ville:new" }
    methods:  [GET, POST]

ville_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionBundle:Ville:edit" }
    methods:  [GET, POST]

ville_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionBundle:Ville:delete" }
    methods:  DELETE
