voyageur_index:
    path:     /
    defaults: { _controller: "GestionBundle:Voyageur:index" }
    methods:  GET

voyageur_show:
    path:     /{id}/show
    defaults: { _controller: "GestionBundle:Voyageur:show" }
    methods:  GET

voyageur_new:
    path:     /new
    defaults: { _controller: "GestionBundle:Voyageur:new" }
    methods:  [GET, POST]

voyageur_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionBundle:Voyageur:edit" }
    methods:  [GET, POST]

voyageur_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionBundle:Voyageur:delete" }
    methods:  DELETE
