<?php

namespace Gestion\GestionBundle\Repository;

/**
 * CompteVoyageurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteVoyageurRepository extends \Doctrine\ORM\EntityRepository
{
}
