<?php

namespace Gestion\GestionBundle\Repository;

/**
 * VilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VilleRepository extends \Doctrine\ORM\EntityRepository
{
      public function getVilleArrivee($id) {
        return $this->createQueryBuilder('v')
                        ->Where('v.id <> :id')
                        ->setParameter('id', $id)
                        ->getQuery()
                        ->getResult();
    }
}
