<?php

namespace Gestion\GestionBundle\Repository;

/**
 * VoyageurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoyageurRepository extends \Doctrine\ORM\EntityRepository
{
}
