gestion_routing_visiteur:
    resource: "@GestionBundle/Resources/config/routingvisiteur.yml"
    prefix:   /

gestion:
    resource: "@GestionBundle/Resources/config/routing.yml"
    prefix:   /admin

user:
    resource: "@UsersBundle/Resources/config/routing.yml"
    prefix:   /admin

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"