<?php

namespace UsersBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository {

    public function findAll() {
        return $this->findBy(array(), array('id' => 'DESC'));
    }

}
