parameters:
    utilisateur_mailer.class: UsersBundle\Services\Mailer

services:
    login_listener:
        class: 'UsersBundle\EventListener\LoginListener'
        arguments: ['@security.authorization_checker', '@router', '@event_dispatcher']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login', method: onSecurityInteractiveLogin }

    utilisateur_mailer:
        class: %utilisateur_mailer.class%
        arguments: ['@mailer','@templating']